# Configmap 文件，注意修改数据库配置、用户名、密码参数
kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-apollo-config-server-dev
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://mysql.public:3306/DevApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = root
    spring.datasource.password = hashquark
    eureka.service.url = http://statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev:8080/eureka/,http://statefulset-apollo-config-server-dev-1.service-apollo-meta-server-dev:8080/eureka/,http://statefulset-apollo-config-server-dev-2.service-apollo-meta-server-dev:8080/eureka/
---
kind: Service
apiVersion: v1
metadata:
  name: service-apollo-meta-server-dev
  labels:
    app: service-apollo-meta-server-dev
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: pod-apollo-config-server-dev
---
kind: Service
apiVersion: v1
metadata:
  name: service-apollo-config-server-dev
  labels:
    app: service-apollo-config-server-dev
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: pod-apollo-config-server-dev
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: statefulset-apollo-config-server-dev
  labels:
    app: statefulset-apollo-config-server-dev
spec:
  serviceName: service-apollo-meta-server-dev
  replicas: 3
  selector:
    matchLabels:
      app: pod-apollo-config-server-dev
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-apollo-config-server-dev
    spec:
      containers:
      - image: harbor.hashquark-dev.net/public/apollo-config-server:v1.4.0
        name: container-apollo-config-server-dev
        ports:
        - containerPort: 8080
        env:
        - name: APOLLO_CONFIG_SERVICE_NAME
          value: "service-apollo-config-server-dev.public"   #修改namespace名称
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds:  120
          periodSeconds: 10
        volumeMounts:
        - name: volume-configmap-apollo-config-server-dev
          mountPath: /apollo-config-server/config/application-github.properties
          subPath: application-github.properties
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: volume-configmap-apollo-config-server-dev
        configMap:
          name: configmap-apollo-config-server-dev
          items:
          - key: application-github.properties
            path: application-github.properties