kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-apollo-admin-server-dev
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://mysql.public:3306/DevApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = root
    spring.datasource.password = hashquark
    eureka.service.url = http://statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev:8080/eureka/,http://statefulset-apollo-config-server-dev-1.service-apollo-meta-server-dev:8080/eureka/,http://statefulset-apollo-config-server-dev-2.service-apollo-meta-server-dev:8080/eureka/
---
kind: Service
apiVersion: v1
metadata:
  name: service-apollo-admin-server-dev
  labels:
    app: service-apollo-admin-server-dev
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: pod-apollo-admin-server-dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-apollo-admin-server-dev
  labels:
    app: deployment-apollo-admin-server-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-apollo-admin-server-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: pod-apollo-admin-server-dev
    spec:
      initContainers:
      - image: harbor.hashquark-dev.net/public/alpine-bash:3.8
        name: check-service-apollo-config-server-dev
        command: ['bash', '-c', "curl --connect-timeout 2 --max-time 5 --retry 60 --retry-delay 1 --retry-max-time 120 service-apollo-config-server-dev.public:8080"]  #修改namespace
      containers:
      - image: harbor.hashquark-dev.net/public/apollo-admin-server:v1.4.0
        name: container-apollo-admin-server-dev
        ports:
        - containerPort: 8090
        env:
        - name: APOLLO_ADMIN_SERVICE_NAME
          value: "service-apollo-admin-server-dev.public"   #修改namespace
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          tcpSocket:
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8090
          initialDelaySeconds: 120
          periodSeconds: 10
        volumeMounts:
        - name: volume-configmap-apollo-admin-server-dev
          mountPath: /apollo-admin-server/config/application-github.properties
          subPath: application-github.properties
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: volume-configmap-apollo-admin-server-dev
        configMap:
          name: configmap-apollo-admin-server-dev
          items:
          - key: application-github.properties
            path: application-github.properties