kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-apollo-config-server-prod
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://mysql.public:3306/ProdApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = root
    spring.datasource.password = hashquark
    eureka.service.url = http://statefulset-apollo-config-server-prod-0.service-apollo-meta-server-prod:8080/eureka/,http://statefulset-apollo-config-server-prod-1.service-apollo-meta-server-prod:8080/eureka/,http://statefulset-apollo-config-server-prod-2.service-apollo-meta-server-prod:8080/eureka/
---
kind: Service
apiVersion: v1
metadata:
  name: service-apollo-meta-server-prod
  labels:
    app: service-apollo-meta-server-prod
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: pod-apollo-config-server-prod
---
kind: Service
apiVersion: v1
metadata:
  name: service-apollo-config-server-prod
  labels:
    app: service-apollo-config-server-prod
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: pod-apollo-config-server-prod
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: statefulset-apollo-config-server-prod
  labels:
    app: statefulset-apollo-config-server-prod
spec:
  serviceName: service-apollo-meta-server-prod
  replicas: 3
  selector:
    matchLabels:
      app: pod-apollo-config-server-prod
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-apollo-config-server-prod
    spec:
      containers:
      - image: harbor.hashquark-dev.net/public/apollo-config-server:v1.4.0
        name: container-apollo-config-server-prod
        ports:
        - containerPort: 8080
        env:
        - name: APOLLO_CONFIG_SERVICE_NAME
          value: "service-apollo-config-server-prod.public"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
        volumeMounts:
        - name: volume-configmap-apollo-config-server-prod
          mountPath: /apollo-config-server/config/application-github.properties
          subPath: application-github.properties
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: volume-configmap-apollo-config-server-prod
        configMap:
          name: configmap-apollo-config-server-prod
          items:
          - key: application-github.properties
            path: application-github.properties