kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-apollo-admin-server-prod
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://mysql.public:3306/ProdApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = root
    spring.datasource.password = hashquark
    eureka.service.url = http://statefulset-apollo-config-server-prod-0.service-apollo-meta-server-prod:8080/eureka/,http://statefulset-apollo-config-server-prod-1.service-apollo-meta-server-prod:8080/eureka/,http://statefulset-apollo-config-server-prod-2.service-apollo-meta-server-prod:8080/eureka/
---
kind: Service
apiVersion: v1
metadata:
  name: service-apollo-admin-server-prod
  labels:
    app: service-apollo-admin-server-prod
spec:
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
  selector:
    app: pod-apollo-admin-server-prod  

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-apollo-admin-server-prod
  labels:
    app: deployment-apollo-admin-server-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-apollo-admin-server-prod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: pod-apollo-admin-server-prod
    spec:
      initContainers:
      - image: harbor.hashquark-dev.net/public/alpine-bash:3.8
        name: check-service-apollo-config-server-prod
        command: ['bash', '-c', "curl --connect-timeout 2 --max-time 5 --retry 50 --retry-delay 1 --retry-max-time 120 service-apollo-config-server-prod.public:8080"]
      containers:
      - image: harbor.hashquark-dev.net/public/apollo-admin-server:v1.4.0
        name: container-apollo-admin-server-prod
        ports:
        - containerPort: 8090
        env:
        - name: APOLLO_ADMIN_SERVICE_NAME
          value: "service-apollo-admin-server-prod.mydlqcloud"
        readinessProbe:
          tcpSocket:
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8090
          initialDelaySeconds: 120
          periodSeconds: 10
        volumeMounts:
        - name: volume-configmap-apollo-admin-server-prod
          mountPath: /apollo-admin-server/config/application-github.properties
          subPath: application-github.properties
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: volume-configmap-apollo-admin-server-prod
        configMap:
          name: configmap-apollo-admin-server-prod
          items:
          - key: application-github.properties
            path: application-github.properties