apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: docker-for-desktop-cluster
- cluster:
    certificate-authority-data: aaaaaaaa
    server: https://152.32.130.135:6443
  name: kubernetes-152.32
- cluster:
    certificate-authority-data: bbbbbbbb
    server: https://172.20.0.23:6443
  name: kubernetes-172.23
contexts:
- context:
    cluster: docker-for-desktop-cluster
    user: docker-for-desktop
  name: docker-for-desktop
- context:
    cluster: kubernetes-152.32
    user: admin
  name: kubernetes-152.32
- context:
    cluster: kubernetes-172.23
    user: kubernetes-admin
  name: kubernetes-172.23
current-context: docker-for-desktop
kind: Config
preferences: {}
users:
- name: docker-for-desktop
  user:
    client-certificate-data: 1111111
    client-key-data: 22222222
- name: kubernetes-admin
  user:
    client-certificate-data: 3333333
    client-key-data: 44444444