apiVersion: v1
kind: Pod
metadata:
  name: nginxweb
spec:
  initContainers:
  - image: dolphintwo/pod-sample:v2
    name: htmls
    command: ["cp", "/index.html", "/app"]
    volumeMounts:
    - mountPath: /app
      name: app-volume
  containers:
  - image: nginx:1.7.9
    name: nginx
    volumeMounts:
    - name: app-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: app-volume
    emptyDir: {}
