apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume 
spec:
  containers:
  - name: test-secret-volume
    image: busybox:1.30.1
    env: 
      - name: THIS_IS_TEST_ENV
        valueFrom:
          configMapKeyRef:
            name: ui-config
            key: color.good
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: my-secret
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: my-secret
    projected:
      sources:
      - secret:
          name: mysecret

