apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv4-jenkins
  labels:
    pv: nfspv4-jenkins
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/jenkins
    server: 172.20.0.47
  mountOptions:
    - nolock
    - nfsvers=4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: jenkins-home
spec:
     accessModes:
       - ReadWriteMany
     resources:
       requests:
         storage: 30Gi
     selector:
       matchLabels:
         pv: nfspv4-jenkins
